(() => {
  'use strict';
  // Global Mini-Game audio mix: +50% SFX, safely capped to avoid clipping.
  function __ict8SfxGain(value) {
    return Math.min(1, Math.max(0, Number(value) || 0) * 1.5);
  }


  const GAME_ID='code-snake';
  const GRID=20;
  const MAX_DPR=2;
  const TOKENS=['</>','{}',';','JS','CSS','HTML','01','()','[]'];
  const runtime={built:false,open:false,state:'ready',bridge:null,onBack:null,onClose:null,onReward:null,overlay:null,shell:null,canvas:null,ctx:null,scoreEl:null,lengthEl:null,pausePanel:null,overPanel:null,finalScore:null,finalBest:null,finalTokens:null,finalXp:null,rewardNote:null,soundBtn:null,pauseBtn:null,raf:0,lastFrame:0,accum:0,view:{w:520,h:520,dpr:1},snake:[],prevSnake:[],dir:{x:1,y:0},queued:[],food:null,score:0,tokens:0,round:null,bestVisible:0,longestVisible:0,soundEnabled:true,audioContext:null,resizeTimer:0,swipeStart:null,fx:[],stepProgress:0};
  const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));

  function build(){
    if(runtime.built)return;
    const overlay=document.createElement('div');overlay.id='codeSnakeOverlay';overlay.className='xp-games-game-overlay code-snake-overlay';overlay.hidden=true;overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-label','Code Snake mini-game');
    overlay.innerHTML=`
      <section class="code-snake-shell">
        <div class="code-snake-topbar"><button type="button" data-code-snake-back>← MINI-GAMES</button><button type="button" data-code-snake-sound aria-label="Toggle sound">🔊</button><button type="button" data-code-snake-pause aria-label="Pause game">Ⅱ</button><button type="button" data-code-snake-close aria-label="Close CODE SNAKE">×</button></div>
        <div class="code-snake-title"><strong>🐍 CODE SNAKE</strong><span>20 × 20 GRID</span></div>
        <div class="code-snake-hud"><div><small>SCORE</small><strong data-code-snake-score>0</strong></div><div><small>CHAIN</small><strong data-code-snake-length>4</strong></div></div>
        <div class="code-snake-board-wrap"><canvas class="code-snake-canvas" aria-label="CODE SNAKE board"></canvas></div>
        <div class="code-snake-help">Swipe on phone · Arrow Keys / WASD on desktop</div>
        <div class="code-snake-panel" data-code-snake-ready><div class="code-snake-panel-card"><span class="code-snake-hero">🐍</span><h2>CODE SNAKE</h2><p>Collect the code. Grow the chain.</p><button class="primary" type="button" data-code-snake-start>START</button></div></div>
        <div class="code-snake-panel" data-code-snake-pause-panel hidden><div class="code-snake-panel-card"><h2>PAUSED</h2><p>Your digital chain is safe.</p><button class="primary" type="button" data-code-snake-resume>RESUME</button></div></div>
        <div class="code-snake-panel" data-code-snake-over hidden><div class="code-snake-panel-card"><h2>GAME OVER</h2><div class="code-snake-stats"><div><small>Score</small><strong data-code-snake-final-score>0</strong></div><div><small>Best</small><strong data-code-snake-final-best>0</strong></div><div><small>Tokens</small><strong data-code-snake-final-tokens>0</strong></div><div class="xp"><small>XP Earned</small><strong data-code-snake-final-xp>+0</strong></div></div><p class="code-snake-reward-note" data-code-snake-reward-note>Checking reward…</p><div class="code-snake-actions"><button class="primary" type="button" data-code-snake-again>PLAY AGAIN</button><button type="button" data-code-snake-hub>MINI-GAMES</button><button type="button" data-code-snake-close-result>CLOSE</button></div></div></div>
      </section>`;
    document.body.appendChild(overlay);runtime.overlay=overlay;runtime.shell=overlay.querySelector('.code-snake-shell');runtime.canvas=overlay.querySelector('.code-snake-canvas');runtime.ctx=runtime.canvas.getContext('2d',{alpha:false});runtime.scoreEl=overlay.querySelector('[data-code-snake-score]');runtime.lengthEl=overlay.querySelector('[data-code-snake-length]');runtime.pausePanel=overlay.querySelector('[data-code-snake-pause-panel]');runtime.overPanel=overlay.querySelector('[data-code-snake-over]');runtime.finalScore=overlay.querySelector('[data-code-snake-final-score]');runtime.finalBest=overlay.querySelector('[data-code-snake-final-best]');runtime.finalTokens=overlay.querySelector('[data-code-snake-final-tokens]');runtime.finalXp=overlay.querySelector('[data-code-snake-final-xp]');runtime.rewardNote=overlay.querySelector('[data-code-snake-reward-note]');runtime.soundBtn=overlay.querySelector('[data-code-snake-sound]');runtime.pauseBtn=overlay.querySelector('[data-code-snake-pause]');
    overlay.querySelector('[data-code-snake-start]').addEventListener('click',startRound);overlay.querySelector('[data-code-snake-resume]').addEventListener('click',resume);overlay.querySelector('[data-code-snake-again]').addEventListener('click',resetReady);overlay.querySelector('[data-code-snake-back]').addEventListener('click',returnToHub);overlay.querySelector('[data-code-snake-hub]').addEventListener('click',returnToHub);overlay.querySelector('[data-code-snake-close]').addEventListener('click',closeAll);overlay.querySelector('[data-code-snake-close-result]').addEventListener('click',closeAll);runtime.soundBtn.addEventListener('click',toggleSound);runtime.pauseBtn.addEventListener('click',()=>{if(runtime.state==='playing')pause();else if(runtime.state==='paused')resume();});
    runtime.canvas.addEventListener('pointerdown',e=>{if(!runtime.open)return;e.preventDefault();runtime.swipeStart={x:e.clientX,y:e.clientY};try{runtime.canvas.setPointerCapture(e.pointerId);}catch(_){}});runtime.canvas.addEventListener('pointerup',e=>{if(!runtime.open||!runtime.swipeStart)return;e.preventDefault();const dx=e.clientX-runtime.swipeStart.x,dy=e.clientY-runtime.swipeStart.y;runtime.swipeStart=null;if(Math.max(Math.abs(dx),Math.abs(dy))<16)return;if(Math.abs(dx)>Math.abs(dy))queueDirection(dx>0?1:-1,0);else queueDirection(0,dy>0?1:-1);});
    overlay.addEventListener('touchmove',e=>{if(runtime.open)e.preventDefault();},{passive:false});
    document.addEventListener('keydown',e=>{if(!runtime.open)return;const key=e.key.toLowerCase();let d=null;if(key==='arrowup'||key==='w')d=[0,-1];else if(key==='arrowdown'||key==='s')d=[0,1];else if(key==='arrowleft'||key==='a')d=[-1,0];else if(key==='arrowright'||key==='d')d=[1,0];else if(key==='p'){if(runtime.state==='playing')pause();else if(runtime.state==='paused')resume();return;}if(!d)return;if(e.target?.closest?.('input,textarea,select'))return;e.preventDefault();queueDirection(d[0],d[1]);});
    document.addEventListener('visibilitychange',()=>{if(runtime.open&&document.hidden&&runtime.state==='playing')pause();});window.addEventListener('blur',()=>{if(runtime.open&&runtime.state==='playing')pause();});window.addEventListener('resize',queueResize,{passive:true});window.addEventListener('orientationchange',()=>setTimeout(queueResize,100),{passive:true});runtime.built=true;
  }

  function queueResize(){if(!runtime.open)return;clearTimeout(runtime.resizeTimer);runtime.resizeTimer=setTimeout(resizeCanvas,70)}
  function resizeCanvas(){const rect=runtime.canvas.getBoundingClientRect();const w=Math.max(260,rect.width||520),h=Math.max(260,rect.height||520),dpr=Math.max(1,Math.min(MAX_DPR,Number(window.devicePixelRatio || 1)));runtime.canvas.width=Math.round(w*dpr);runtime.canvas.height=Math.round(h*dpr);runtime.ctx.setTransform(dpr,0,0,dpr,0,0);runtime.view={w,h,dpr}}
  function getAudio(){if(!runtime.soundEnabled)return null;try{if(!runtime.audioContext)runtime.audioContext=new (window.AudioContext || window.webkitAudioContext)();if(runtime.audioContext.state==='suspended')runtime.audioContext.resume().catch(()=>{});return runtime.audioContext}catch(_){return null}}
  function tone(kind){const ctx=getAudio();if(!ctx)return;const o=ctx.createOscillator(),g=ctx.createGain(),now=ctx.currentTime;const t=kind==='eat'?[520,860,.07,.05]:kind==='bonus'?[700,1400,.12,.06]:[180,70,.2,.07];o.type=kind==='crash'?'sawtooth':'square';o.frequency.setValueAtTime(t[0],now);o.frequency.exponentialRampToValueAtTime(t[1],now+t[2]);g.gain.setValueAtTime(__ict8SfxGain(t[3]),now);g.gain.exponentialRampToValueAtTime(.001,now+t[2]);o.connect(g).connect(ctx.destination);o.start();o.stop(now+t[2]+.02)}
  function toggleSound(){runtime.soundEnabled=!runtime.soundEnabled;runtime.soundBtn.textContent=runtime.soundEnabled?'🔊':'🔇';runtime.bridge?.setSoundEnabled?.(runtime.soundEnabled)}

  function initialSnake(){return[{x:9,y:10},{x:8,y:10},{x:7,y:10},{x:6,y:10}]}
  function resetReady(){runtime.state='ready';runtime.snake=initialSnake();runtime.prevSnake=runtime.snake.map(s=>({...s}));runtime.dir={x:1,y:0};runtime.queued=[];runtime.food=randomFood();runtime.score=0;runtime.tokens=0;runtime.round=null;runtime.accum=0;runtime.fx=[];runtime.scoreEl.textContent='0';runtime.lengthEl.textContent=String(runtime.snake.length);runtime.overlay.querySelector('[data-code-snake-ready]').hidden=false;runtime.pausePanel.hidden=true;runtime.overPanel.hidden=true;runtime.pauseBtn.textContent='Ⅱ';runtime.lastFrame=performance.now()}
  function startRound(){if(runtime.state!=='ready')return;runtime.overlay.querySelector('[data-code-snake-ready]').hidden=true;runtime.snake=initialSnake();runtime.prevSnake=runtime.snake.map(s=>({...s}));runtime.dir={x:1,y:0};runtime.queued=[];runtime.food=randomFood();runtime.score=0;runtime.tokens=0;runtime.accum=0;runtime.state='playing';try{runtime.round=runtime.bridge?.beginRound?.(GAME_ID)||null}catch(_){runtime.round=null}runtime.lastFrame=performance.now()}
  function pause(){if(runtime.state!=='playing')return;runtime.state='paused';runtime.pausePanel.hidden=false;runtime.pauseBtn.textContent='▶'}
  function resume(){if(runtime.state!=='paused')return;runtime.state='playing';runtime.pausePanel.hidden=true;runtime.pauseBtn.textContent='Ⅱ';runtime.lastFrame=performance.now()}
  function queueDirection(x,y){if(runtime.state!=='playing')return;const base=runtime.queued.length?runtime.queued[runtime.queued.length-1]:runtime.dir;if(base.x===-x&&base.y===-y)return;if(base.x===x&&base.y===y)return;if(runtime.queued.length<2)runtime.queued.push({x,y})}
  function occupied(x,y){return runtime.snake.some(s=>s.x===x&&s.y===y)}
  function randomFood(){let x=0,y=0,tries=0;do{x=Math.floor(Math.random()*GRID);y=Math.floor(Math.random()*GRID);tries++}while(occupied(x,y)&&tries<100);const bonus=Math.random()<.08;return{x,y,bonus,label:bonus?'★':TOKENS[Math.floor(Math.random()*TOKENS.length)]}}
  function intervalMs(){if(runtime.score>=40)return 100;if(runtime.score>=20)return 114;if(runtime.score>=10)return 128;return 145}
  function step(){if(runtime.queued.length)runtime.dir=runtime.queued.shift();runtime.prevSnake=runtime.snake.map(s=>({...s}));const head=runtime.snake[0];const next={x:head.x+runtime.dir.x,y:head.y+runtime.dir.y};if(next.x<0||next.y<0||next.x>=GRID||next.y>=GRID||runtime.snake.some((s,i)=>i<runtime.snake.length-1&&s.x===next.x&&s.y===next.y)){finishRound();return}runtime.snake.unshift(next);if(runtime.food&&next.x===runtime.food.x&&next.y===runtime.food.y){const pts=runtime.food.bonus?3:1;runtime.score+=pts;runtime.tokens++;runtime.fx.push({x:next.x,y:next.y,text:runtime.food.bonus?'+3 BONUS':'+1',age:0,life:.7});tone(runtime.food.bonus?'bonus':'eat');runtime.food=randomFood();}else runtime.snake.pop();runtime.scoreEl.textContent=String(runtime.score);runtime.lengthEl.textContent=String(runtime.snake.length)}
  function update(dt){runtime.fx.forEach(f=>f.age+=dt);runtime.fx=runtime.fx.filter(f=>f.age<f.life);if(runtime.state!=='playing')return;runtime.accum+=dt*1000;const iv=intervalMs();let guard=0;while(runtime.accum>=iv&&runtime.state==='playing'&&guard<3){runtime.accum-=iv;step();guard++}runtime.stepProgress=clamp(runtime.accum/iv,0,1)}

  async function finishRound(){if(runtime.state!=='playing')return;runtime.state='gameover';tone('crash');runtime.shell.classList.remove('impact');void runtime.shell.offsetWidth;runtime.shell.classList.add('impact');runtime.finalScore.textContent=String(runtime.score);runtime.finalBest.textContent=String(Math.max(runtime.bestVisible,runtime.score));runtime.finalTokens.textContent=String(runtime.tokens);runtime.finalXp.textContent='+0';runtime.rewardNote.className='code-snake-reward-note';runtime.rewardNote.textContent=runtime.round?'Checking reward…':'Practice run — account reward unavailable.';runtime.overPanel.hidden=false;if(!runtime.round?.sessionId||!runtime.bridge?.claimRound)return;try{const result=await runtime.bridge.claimRound(runtime.round.sessionId,{score:runtime.score,metrics:{tokens:runtime.tokens,longestSnake:runtime.snake.length}});const rec=result?.gameRecord||result?.gameRecords?.codeSnake||{};runtime.bestVisible=Math.max(runtime.bestVisible,Number(rec.bestScore||0),Number(result?.bestScore||0));runtime.longestVisible=Math.max(runtime.longestVisible,Number(rec.longestSnake||0));runtime.finalBest.textContent=String(runtime.bestVisible);runtime.finalXp.textContent=`+${Math.max(0,Number(result?.awardedXp||0))}`;if(result?.loginRequired){runtime.rewardNote.className='code-snake-reward-note warn';runtime.rewardNote.textContent='Practice mode — log in as a student to earn account XP.'}else if(result?.syncFailed){runtime.rewardNote.className='code-snake-reward-note warn';runtime.rewardNote.textContent='XP could not sync. No account XP was added.'}else if(result?.capReached&&Number(result.awardedXp||0)===0){runtime.rewardNote.className='code-snake-reward-note warn';runtime.rewardNote.textContent='Daily Mini-Game XP limit reached. Keep growing your chain!'}else{runtime.rewardNote.className='code-snake-reward-note success';runtime.rewardNote.textContent=Number(result?.awardedXp||0)>0?`Reward added safely · Today's Game XP: ${result.todayXp}/${result.dailyCap}`:'Collect more code tokens to reach an XP tier.'}try{runtime.onReward?.(result)}catch(_){}}catch(_){runtime.rewardNote.className='code-snake-reward-note warn';runtime.rewardNote.textContent='Reward could not be processed. No XP was added.'}}

  function draw(){const ctx=runtime.ctx,{w,h}=runtime.view,cell=Math.min(w,h)/GRID,ox=(w-cell*GRID)/2,oy=(h-cell*GRID)/2;ctx.fillStyle='#06111b';ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(45,212,191,.07)';ctx.lineWidth=1;for(let i=0;i<=GRID;i++){ctx.beginPath();ctx.moveTo(ox+i*cell,oy);ctx.lineTo(ox+i*cell,oy+cell*GRID);ctx.stroke();ctx.beginPath();ctx.moveTo(ox,oy+i*cell);ctx.lineTo(ox+cell*GRID,oy+i*cell);ctx.stroke()}if(runtime.food){const x=ox+(runtime.food.x+.5)*cell,y=oy+(runtime.food.y+.5)*cell;ctx.save();ctx.fillStyle=runtime.food.bonus?'#f59e0b':'#0ea5e9';ctx.shadowColor=runtime.food.bonus?'#fbbf24':'#38bdf8';ctx.shadowBlur=14;ctx.beginPath();ctx.roundRect?ctx.roundRect(x-cell*.38,y-cell*.34,cell*.76,cell*.68,cell*.15):ctx.rect(x-cell*.38,y-cell*.34,cell*.76,cell*.68);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#fff';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`900 ${Math.max(8,cell*.30)}px system-ui`;ctx.fillText(runtime.food.label,x,y);ctx.restore()}
    runtime.snake.forEach((seg,i)=>{const prev=runtime.prevSnake[i]||seg;const t=runtime.state==='playing'?runtime.stepProgress:1;const gx=prev.x+(seg.x-prev.x)*t,gy=prev.y+(seg.y-prev.y)*t;const x=ox+gx*cell+cell*.09,y=oy+gy*cell+cell*.09,s=cell*.82;ctx.fillStyle=i===0?'#2dd4bf':`hsl(${174-i*.8} 70% ${Math.max(36,58-i*.45)}%)`;ctx.beginPath();ctx.roundRect?ctx.roundRect(x,y,s,s,cell*.18):ctx.rect(x,y,s,s);ctx.fill();if(i===0){ctx.fillStyle='#06201f';const ex=x+s*.66,ey=y+s*.31;ctx.beginPath();ctx.arc(ex,ey,Math.max(1.5,cell*.06),0,Math.PI*2);ctx.fill()}});runtime.fx.forEach(f=>{const t=f.age/f.life;ctx.save();ctx.globalAlpha=1-t;ctx.fillStyle='#fde68a';ctx.textAlign='center';ctx.font=`900 ${Math.max(11,cell*.36)}px system-ui`;ctx.fillText(f.text,ox+(f.x+.5)*cell,oy+(f.y+.4)*cell-t*26);ctx.restore()})}
  function frame(time){runtime.raf=0;if(!runtime.open)return;const dt=clamp((time-(runtime.lastFrame||time))/1000,0,.05);runtime.lastFrame=time;update(dt);draw();runtime.raf=requestAnimationFrame(frame)}
  function returnToHub(){const cb=runtime.onBack;closeInternal();try{cb?.()}catch(_){}}
  function closeAll(){const cb=runtime.onClose;closeInternal();try{cb?.()}catch(_){}}
  function closeInternal(){if(!runtime.open)return;runtime.open=false;runtime.overlay.hidden=true;document.body.classList.remove('code-snake-active');if(runtime.raf)cancelAnimationFrame(runtime.raf);runtime.raf=0;runtime.state='ready';runtime.round=null;runtime.pausePanel.hidden=true;runtime.overPanel.hidden=true}
  function open(options={}){build();runtime.bridge=options.bridge||window.ICT8_XP_MINIGAMES_BRIDGE||null;runtime.onBack=typeof options.onBack==='function'?options.onBack:null;runtime.onClose=typeof options.onClose==='function'?options.onClose:null;runtime.onReward=typeof options.onReward==='function'?options.onReward:null;const snap=runtime.bridge?.getSnapshot?.()||{};runtime.soundEnabled=snap.soundEnabled!==false;runtime.soundBtn.textContent=runtime.soundEnabled?'🔊':'🔇';runtime.bestVisible=Math.max(0,Number(snap.gameRecords?.codeSnake?.bestScore||snap.bestScores?.codeSnake||0));runtime.longestVisible=Math.max(0,Number(snap.gameRecords?.codeSnake?.longestSnake||0));runtime.open=true;runtime.overlay.hidden=false;document.body.classList.add('code-snake-active');requestAnimationFrame(()=>{resizeCanvas();resetReady();if(!runtime.raf)runtime.raf=requestAnimationFrame(frame)})}
  window.ICT8CodeSnake=Object.freeze({open,close:closeInternal,isOpen:()=>runtime.open});
})();
